services:
    kdrmklabs_ticket.user_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - %kdrmklabs_ticket.model.user.class%
    kdrmklabs_ticket.ticket_service:
        class: Kdrmklabs\Bundle\TicketBundle\Services\TicketService
        arguments:
            - "@service_container"
    kdrmklabs_ticket.listener:
        class: Kdrmklabs\Bundle\TicketBundle\EventListener\LoadMetadata
        arguments:
            - %kdrmklabs_ticket.model.user.class%
            - %kdrmklabs_ticket.model.user.primary_key%
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }